# Generated by Django 4.1.6 on 2023-02-09 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(12)])),
                ('body', models.TextField()),
            ],
        ),
    ]
