# Generated by Django 4.1.6 on 2023-02-09 23:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('magazine_pdf_file', models.FileField(upload_to='magazine/magazine_pdf_files')),
                ('cover_image', models.ImageField(upload_to='magazine/magazine_images')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(upload_to='magazine/page_images')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='magazine.magazine')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_profile_picture', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='magazine.page')),
            ],
        ),
    ]
