# Generated by Django 4.2 on 2023-04-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
        migrations.AddField(
            model_name='comment',
            name='magazine',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='magazine.magazine'),
            preserve_default=False,
        ),
    ]
